name: Test
on:
  push:
    branches: [test]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/test1
    steps:
      - uses: actions/checkout@v2
      - run: sed -e "s/##utbotgo_dir/${PWD//\//\\\/}/" < ../../utbotgo/utbotgo.sh > ../utbotgo; sudo chmod ugo+x ../utbotgo
      - run: ../utbotgo init
