name: Test
on:
  push:
    branches: [test]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: utbotgo
    steps:
      - uses: actions/checkout@v2
      - run: sed -e "s/##utbotgo_dir/${PWD//\//\\\/}/" < utbotgo.sh > ../examples/utbotgo; sudo chmod ugo+x ../examples/utbotgo
      - run: cd ../examples/test1; ../utbotgo init
